### PR TITLE
Support storing session in files, encryption, and other breaking changes.

### PR DESCRIPTION
**Pull request by sun-jiao**
Hello mezoni. I have recently made some changes to this repository, supporting storing sessions in files and encryption.

Before proceeding with the details, I would like to know the current status of the project. The repository appears to have been inactive for years, and I wanted to confirm whether contributions are still accepted.

Regarding the pull request itself, I have introduced the following breaking changes, I understand that they may not get accepted as inappropriate for the repository:

1. I've abstracted a class called ` SessionStorage` and rewritten the original way of storing sessions in a `Map`  into an implementation, `MemoryStorage`.
2. I've added other implementations to store sessions in files as plain or encrypted text.
3. Other corresponding updates: the example has been updated, and some methods have to be turned into asynchronous ones.
4. Other minor changes, I've reorganized the package, added .gitignore and removed some ignored files.

### CODE REVIEW

**Comment by mezoni** [comment]
Thank you for the work done. But I would like to bring a little clarity to the principle of work.
Currently it works like this.

```dart
  Customer? getCustomer(Request request) {
    final session = Session.getSession(request);
    if (session == null) {
      return null;
    }

    final user = session.data['user'];
    if (user is Customer) {
      return user;
    }

    return null;
  }

  Customer setCustomer(Request request, Customer customer) {
    var session = Session.getSession(request);
    session ??= Session.createSession(request);
    session.data['user'] = customer;
    return customer;
  }
```

And used as such

```dart
Future<Response> handleGet(Request request) async {
  Map<String, Object?> setValues() {
    final values = <String, Object?>{};
    final customerManager = CustomerManager();
    final customer = customerManager.getCustomer(request);
    final config = yamlConfig('config.yaml');
    final oauth = <Map<String, Object?>>[];
    if (config.tryRead<Map<dynamic, dynamic>>('oauth_vk', false) != null) {
      final vkOauth = {
        'name': 'vk.com',
        'uri': Uri.http(
          'oauth.vk.com',
          'authorize',
          {
            'client_id': config.read<int>('oauth_vk.client_id').toString(),
            'redirect_uri': config.read<String>('oauth_vk.redirect_uri'),
            'display': 'page',
            'response_type': 'code',
          },
        ).toString(),
      };
      oauth.add(vkOauth);
    }

    values['oauth'] = oauth;
    if (customer != null) {
      values['customer'] = {'name': '$customer'};
    } else {
      values['customer'] = null;
    }

    return values;
  }

  return renderPage(
    request,
    'auth/login',
    title: 'Авторизация (вход)',
    values: setValues(),
  );
}

Future<Response> handlePost(Request request) async {
  final body = await request.readAsString();
  final formValues = Uri(query: body).queryParameters;
  final login = formValues['login'] ?? ''
    ..trim();
  final password = formValues['password'] ?? ''
    ..trim();
  if (login.isEmpty || password.isEmpty) {
    return redirect(request, 'login');
  }

  final loggedAt = dateTimeToUtc(DateTime.now());
  final loginManager = LoginManager();
  final customer = await loginManager.login(
    loggedAt: loggedAt,
    login: login,
    password: password,
  );

  if (customer != null) {
    final customerManager = CustomerManager();
    customerManager.setCustomer(request, customer);
  }

  return redirect(request, 'login');
}
```

So I have a question. How to store instances of data objects in files during a session?
For example, an instance of the class  `Customer`.
That is, additional data serialization will be required?

**Comment by sun-jiao** [comment]
@mezoni  methods `json.decode` and `encode` have optional params `reviver` and `toEncodable`, I'll add a commit to allow users to specify them. And anyway, the default `MemoryStorage` still works with adding some `await`s.

**Comment by mezoni** [comment]
This library was conceived and created as a simple and quite primitive library in its capabilities for working with cookies and sessions, where the session identifier is stored in cookies, and the session data is stored in memory in a "live form" (that is, not serialized).
From the moment of its creation to the present day, this code has been used in a small online store.
No problems were noticed in the work.
What's the point of making changes to source code that was not originally intended to be changed?
Essentially, this software is what it was designed for.
If significant changes are made, existing code that uses this code will require modification.
But what, at the same time, will be the advantages if this small library copes with its purpose?

In fact, it is part of publicly available private code.
Why is this code publicly available? Because this code is not critically important.

**Comment by sun-jiao** [comment]
@mezoni OK. I think the significant advantage is that the sessions can still be restored after the server is restarted.

I hope to clear up the following question: Are you saying that this package is for your personal use only and you don't want to accept PRs beyond your scope? If so, I might consider publishing it as a new package.

**Comment by sun-jiao** [comment]
Anyway, thanks for your advice, I think it's really useful.

**Comment by mezoni** [comment]
>>  Are you saying that this package is for your personal use only and you don't want to accept PRs beyond your scope? 

This is not for personal use. This is for everyone.
Where do you get these thoughts from? If you are not happy with something, then why should it be an obstacle for everyone else?
There are no restrictions on the use of this software only by me and no one else.

>>  Are you saying that this package is for your personal use only and you don't want to accept PRs beyond your scope? 

Your proposal breaks everything that is possible in this software. What's the point of this? Possibility to save sessions in case of server reboot? Yes, it's cool. But it introduces many restrictions.
1. Not all types of data can be stored in a session
2. The stored data must support serialization.
3. When rebooting the server, you must take into account that data types may have changed and serialization may not work, which means you need to consider the sessions cache clearing function.
4. The session data type itself must also support serialization, or the session data must be stored in a special format with the possibility of partially changing the data in the session (in portions).

This solution does not impose any restrictions on the types of data that can be stored in sessions.
Sessions can store any data.
When the server is rebooted, the data saved in the session is lost. But this is not a problem, because this data is obtained from other sources.
If any changes are made to the data, it is first updated in the original source and, if necessary, then updated in sessions. Everything will depend on how the data will be updated and for what purpose.
The data stored in the session is needed to implement a mechanism for maintaining state for the duration of the session.

**Comment by sun-jiao** [comment]
I meant, are you sharing the package that only meets your own needs so that it can be used by anyone else who has the same needs as you? I'm not saying that the package is proprietary or has any other limitations. I'm sorry for any misunderstanding. I'm not a native English speaker.

**Comment by mezoni** [comment]
In a sense, you are right. Because that is what most people do.
For example, Google has shared a Dart SDK that meets just their own requirements.
And no one can saying that the Dart SDK is proprietary.
So that Dart SDK can be used by anyone else who has the same needs as Google.

**Pull request closed without merging**
